### ISSUE TITLE
Random access denied errors

### ISSUE THREAD

**Issue by mikkohei13** [DINA-Web/slim-taxonomy#8]
Accessing the API on Alpha gives access denied errors randomly:

        Slim Application Error
        The application could not run because of the following error:

        Details

        Type: PDOException
        Code: 1045
        Message: SQLSTATE[HY000] [1045] Access denied for user 'taxonomyuser'@'172.22.0.11' (using password: YES)
        File: /var/www/html/app/src/dependencies.php
        Line: 47
        Trace

        #0 /var/www/html/app/src/dependencies.php(47): PDO->__construct('mysql:host=db;d...', 'taxonomyuser', 'password')
        #1 /var/www/html/app/vendor/pimple/pimple/src/Pimple/Container.php(118): {closure}(Object(Slim\Container))
        #2 /var/www/html/app/vendor/slim/slim/Slim/Container.php(123): Pimple\Container->offsetGet('db')
        #3 /var/www/html/app/src/routes.php(49): Slim\Container->get('db')
        #4 [internal function]: Closure->{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
        #5 /var/www/html/app/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(41): call_user_func(Object(Closure), Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
        #6 /var/www/html/app/vendor/slim/slim/Slim/Route.php(344): Slim\Handlers\Strategies\RequestResponse->__invoke(Object(Closure), Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
        #7 /var/www/html/app/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(122): Slim\Route->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
        #8 /var/www/html/app/vendor/slim/slim/Slim/Route.php(316): Slim\Route->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
        #9 /var/www/html/app/vendor/slim/slim/Slim/App.php(476): Slim\Route->run(Object(Slim\Http\Request), Object(Slim\Http\Response))
        #10 /var/www/html/app/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(122): Slim\App->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
        #11 /var/www/html/app/vendor/slim/slim/Slim/App.php(370): Slim\App->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
        #12 /var/www/html/app/vendor/slim/slim/Slim/App.php(295): Slim\App->process(Object(Slim\Http\Request), Object(Slim\Http\Response))
        #13 /var/www/html/app/public/index.php(32): Slim\App->run()
        #14 {main}

**Comment by mikkohei13** [comment]
Thing to try out: Refer to the database container using a container_name (e.g. slim-taxonomy-db) set in docker-compose, instead of the service name (db).

**Comment by mikkohei13** [comment]
Fixed by #12
